name: Publish

on:
  push:
    branches:
      - 'root'

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1

        with:
          java-version: 1.14

      - name: List files
        run: ls

      - name: List templates
        run: ls templates/**/*

      - name: Build site
        run: sh ./build.sh

      - name: Copy assets
        run: cp -R site/static build/static

      - name: Copy CNAME
        run: cp CNAME build

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
